### ISSUE TITLE
Some of the data is mixed up

### ISSUE THREAD

**Issue by motoras** [romania/coduri-postale#3]
Hi guys, I just wanted to let you know that some of the data in the csv file it is not sorted properly.
Between lines 7145 and 7300 there are places from both Calarasi and Ialomita counties, while between lines 7730 and 8148 various towns and villages from Giurgiu, Ialomita, Ilfov, Dambovita and Calarasi are mixed up. Also the last two entries 13755 and 13756 are also out of place.

**Comment by postal-code** [comment]
Hello @motoras and thank you for the notice. Would you care updating the file in case you managed to fix it?

**Comment by motoras** [comment]
Sure, but is it ok to simply sort them by county or you want also for each county to put first the county capital?(right now it looks like first city for each county is either the capital or the one with the largest population).  Also shall we sort them inside each  county by name or by population?

**Comment by motoras** [comment]
Sorry,  guys I messed up, I posted my issue on the wrong project.  This issue belongs to romania/localitati project.

See https://github.com/romania/localitati/pull/16
